name: on push to main

on:
  push:
    branches:
      - main

  # Allow manually running this workflow.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  detect_changed_files:
    name: detect changed files
    permissions:
      contents: read
      pull-requests: read
    uses: EarthmanMuons/reusable-workflows/.github/workflows/detect-changed-files.yml@main

  deploy_github_pages:
    name: deploy github pages
    permissions:
      actions: read
      id-token: write
      pages: write
    needs: detect_changed_files
    if: |-
      needs.detect_changed_files.outputs.rust == 'true'
      || github.event_name == 'workflow_dispatch'
    uses: EarthmanMuons/reusable-workflows/.github/workflows/deploy-github-pages-rust.yml@main

  tag_untagged_releases:
    name: tag untagged releases
    needs: detect_changed_files
    if: |-
      needs.detect_changed_files.outputs.rust == 'true'
      || github.event_name == 'workflow_dispatch'
    uses: EarthmanMuons/reusable-workflows/.github/workflows/tag-untagged-releases-rust.yml@main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
